<?php

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RmModel extends Model
{
    use HasFactory;

    protected $primaryKey = "id";
    public $timestamps = true;
    public $incrementing = true;
    protected $fillable = [];

    public function beforeSave(){
        return true;
    }
    public function save(array $options = [])
    {
        try {
            if(!$this->beforeSave()){
                return false;
            }

            return parent::save($options); // TODO: Change the autogenerated stub
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage());
        }
    }
}
